HW1
egorgsv/hw_programming pull request #5
Opened 2021-02-22 13:05 UTC by egorgsv

2021-02-23 13:30 UTC, danilasimanok requested changes

2021-02-23 13:30 UTC, danilasimanok commented on HW1/MatrixMult/Matrix.cs
> +            foreach (var line in this.array)
Либо везде, где можно, `var`, либо везде тип. Если крутой, то первое. :)

2021-02-23 13:30 UTC, danilasimanok commented on HW1/MatrixMult/Matrix.cs
> +            if (matrix.m != this.m || matrix.n != this.n)
Если в `obj` -- не матрица, то ты упадешь с `NullPointerException`.

2021-02-23 13:30 UTC, danilasimanok commented on HW1/ResizeArray/Program.cs
> +        static int default_count = 10;
`defaultCount`

2021-02-23 13:30 UTC, danilasimanok commented on HW1/Graph/Graph.cs
> +        //}
Это нужно убрать.

2021-02-23 13:30 UTC, danilasimanok commented on HW1/Graph/Program.cs
> +            path = "/Users/egorgusev/Programming/hw_programming/HW1/Tests/test_data/Graph.txt";
Просто возьми первый аргумент командной строки.

2021-02-23 13:30 UTC, danilasimanok commented on HW1/Graph/Program.cs
> +                String dotCode = "";
Эта переменная не нужна.

2021-02-23 13:30 UTC, danilasimanok commented on HW1/Graph/Program.cs
> +            //string output = outputDot.Generate(new FileDotEngine(), "graph");
Этот комментарий нужно убрать.

2021-02-23 13:30 UTC, danilasimanok commented on HW1/Graph/Program.cs
> +            Console.WriteLine(adjacencyMatrix.ToString());
Эта команда лишняя.

2021-02-23 13:30 UTC, danilasimanok commented on HW1/MatrixMult/MatrixReader.cs
> +        public static Matrix Reader(string _path)
`path`

2021-03-10 14:08 UTC, gsvgit requested changes

2021-03-10 14:08 UTC, gsvgit commented on HW1/MatrixMult/Matrix.cs
> +            isZero(n);
Странное название. Дело же не в проверке некоторого числа на 0.

2021-03-10 14:08 UTC, gsvgit commented on HW1/ResizeArray/Program.cs
> +        static int default_count = 10;
+1

2021-03-10 14:08 UTC, gsvgit commented on HW1/ResizeArray/Program.cs
> +    }
+1

2021-03-11 15:31 UTC, gsvgit approved these changes

2021-03-11 15:32 UTC, merged